# ansible/common.yml
# Common setup for both EC2 instances: Install Docker and Docker Compose.

- name: Common EC2 Setup
  hosts: all
  become: true # Run commands with sudo privileges
  tasks:
    - name: Update yum cache
      yum:
        update_cache: yes

    - name: Install required packages for Docker
      yum:
        name:
          - yum-utils
          - device-mapper-persistent-data
          - lvm2
        state: present

    - name: Add Docker GPG key
      rpm_key:
        state: present
        key: https://download.docker.com/linux/centos/gpg

    - name: Add Docker repository
      get_url:
        url: https://download.docker.com/linux/centos/docker-ce.repo
        dest: /etc/yum.repos.d/docker-ce.repo
        mode: '0644'

    - name: Install Docker Engine
      yum:
        name: docker-ce
        state: present

    - name: Start Docker service
      systemd:
        name: docker
        state: started
        enabled: yes

    - name: Add ec2-user to docker group
      user:
        name: ec2-user
        groups: docker
        append: yes

    - name: Install Docker Compose
      get_url:
        url: https://github.com/docker/compose/releases/download/1.29.2/docker-compose-Linux-x86_64
        dest: /usr/local/bin/docker-compose
        mode: '0755'

    - name: Verify Docker Compose installation
      command: docker-compose --version
      register: docker_compose_version
      changed_when: false
    - debug:
        var: docker_compose_version.stdout_lines

    - name: Install Python (if not already installed by user_data)
      yum:
        name: python3
        state: present
    - name: Ensure pip is installed
      command: python3 -m ensurepip
      args:
        creates: /usr/local/bin/pip3  
    - name: Upgrade pip
      command: pip3 install --upgrade pip
      args:
        creates: /usr/local/bin/pip3    