# ansible/inventory.ini.tpl
# This file is a template and will be dynamically generated by Terraform's user_data.
# For local execution on each EC2 instance.

[backend_servers]
localhost ansible_connection=local ansible_user=ec2-user backend_private_ip=${backend_private_ip}

[game_servers]
localhost ansible_connection=local ansible_user=ec2-user backend_private_ip=${backend_private_ip}
